In [2]:
import numpy as np

array_1 = np.arange(12)**2
print(array_1)
array_2 = np.array([1, 1, 3, 8, 5])
array_1[array_2]


[  0   1   4   9  16  25  36  49  64  81 100 121]


array([ 1,  1,  9, 64, 25])

sentency array_1[array_2] look for number index array

index multidimentional 

In [3]:
example_array = np.array([[0, 0, 0, 0],
                         [1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3],
                         [4, 4, 4, 4]])
index_array = np.array([[1, 0, 4, 2, 1, 0],
                       [0, 0, 0, 4, 4, 3]])
example_array[index_array]

array([[[1, 1, 1, 1],
        [0, 0, 0, 0],
        [4, 4, 4, 4],
        [2, 2, 2, 2],
        [1, 1, 1, 1],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [4, 4, 4, 4],
        [4, 4, 4, 4],
        [3, 3, 3, 3]]])

You can also index for more than one dimension.


In [4]:
array_2_example = np.arange(32).reshape(4, 8)
array_2_example

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [5]:
i = np.array([[0, 2],
             [3, 1]])
j = np.array([[3, 6],
             [3, 7]])
array_2_example[i, j] #(0,3), (2, 6), (3,3), (1, 7)

array([[ 3, 22],
       [27, 15]])

In [6]:
array_2_example[i, 5]

array([[ 5, 21],
       [29, 13]])