In [3]:
import numpy as np

In [4]:
array_example_index = np.arange(28).reshape(4,7)

In [5]:
print(array_example_index)

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]


In [8]:
print(array_example_index[2,4])#18

18


In [10]:
print(array_example_index[0:2,3])#3,10

[ 3 10]


In [11]:
print(array_example_index[1:3,:])

[[ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [16]:
print(array_example_index[1:3,:])

[[ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]]


In [22]:
example_3d = np.arange(64).reshape(4,4,4)

In [23]:
print(example_3d)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]

 [[48 49 50 51]
  [52 53 54 55]
  [56 57 58 59]
  [60 61 62 63]]]


In [25]:
print(example_3d[1,2,3])

27


In [27]:
print(example_3d[3, ...])

[[48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]]


In [29]:
print(example_3d[2,0:1, ...])

[[32 33 34 35]]


Iteration matriz

In [30]:
for element in example_3d.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63


In [31]:
for row in example_3d:
    print(row)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[32 33 34 35]
 [36 37 38 39]
 [40 41 42 43]
 [44 45 46 47]]
[[48 49 50 51]
 [52 53 54 55]
 [56 57 58 59]
 [60 61 62 63]]
