In [7]:
import numpy as np
import random as rg

In [10]:
new_matriz = np.floor(10 * np.random.random((3,4)))

In [11]:
print(new_matriz)

[[1. 5. 7. 7.]
 [7. 0. 9. 0.]
 [0. 1. 4. 8.]]


In [13]:
print(new_matriz.shape)

(3, 4)


In [14]:
print(new_matriz.ravel())

[1. 5. 7. 7. 7. 0. 9. 0. 0. 1. 4. 8.]


In [16]:
print(new_matriz.reshape(2, 6))

[[1. 5. 7. 7. 7. 0.]
 [9. 0. 0. 1. 4. 8.]]


In [17]:
print(new_matriz.T)

[[1. 7. 0.]
 [5. 0. 1.]
 [7. 9. 4.]
 [7. 0. 8.]]


Resize change matriz 

In [22]:
new_matriz.resize((2,6))

In [21]:
print(new_matriz)

[[1. 5.]
 [7. 7.]
 [7. 0.]
 [9. 0.]
 [0. 1.]
 [4. 8.]]
